# The app can be reached at https://immich.<FQDN>:8443
# Change the following variables to adapt the recipe to your needs.
{% set runAsUser = 'nobody' %}
{% set runAsGroup = 'users' %}
# Insert the name of the shared folder you want to use. Make sure the
# configured UID/GID the container is running with has access to that
# directory.
{% set librarySharedFolderName = '<MODIFY>' %}
{% set importSharedFolderName = '<MODIFY>' %}
# !!! Only modify the following manifest if you need to make custom changes. !!!
---
apiVersion: v1
kind: Namespace
metadata:
  name: immich-app
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: immich
spec:
  storageClassName: shared-folder
  capacity:
    storage: 2Gi
  hostPath:
    # This is the path where the immich library will be stored.
    # Insert the name of the shared folder you want to use.
    path: {{ sharedfolder_path(librarySharedFolderName) }}
    type: Directory
  accessModes:
    - "ReadWriteOnce"
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: immich-library
  namespace: immich-app
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: immich
spec:
  storageClassName: shared-folder
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "2Gi"
  volumeName: immich-library
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: immich
  namespace: immich-app
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: immich
spec:
  repo: https://immich-app.github.io/immich-charts
  chart: immich
  version: 0.9.0
  targetNamespace: immich-app
  valuesContent: |-
    securityContext:
      runAsNonRoot: true
      # Specifies the UID for the process running in the container.
      runAsUser: {{ uid(runAsUser) }}
      # Specifies the GID for the process running in the container.
      # Defaults to `users`.
      runAsGroup: {{ gid(runAsGroup) }}
    image:
      tag: v1.119.0
    immich:
      persistence:
        library:
          existingClaim: immich-library
    useDeprecatedPostgresChart: true
    postgresql:
      enabled: true
    redis:
      enabled: true
    persistence:
      # This is the shared folder that is used to import existing files to the immich library.
      # See https://immich.app/docs/guides/external-library/ for more information.
      import:
        enabled: true # Set to false if you do not want to have an external library.
        type: hostPath
        readOnly: true
        mountPath: /srv/import # Use this path in the `Add Import Path` dialog.
        hostPath: {{ sharedfolder_path(importSharedFolderName) }}
        hostPathType: Directory
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich-websecure
  namespace: immich-app
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: immich
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`immich.{{ fqdn() }}`)
      kind: Rule
      services:
        - name: immich-server
          port: 3001
  tls: {}
