# The app can be reached at https://sabnzbd.<FQDN>:8443
# Change the following variables to adapt the recipe to your needs.
{% set runAsUser = 'nobody' %}
{% set runAsGroup = 'users' %}
# Insert the name of the shared folder you want to use. Make sure the
# configured UID/GID the container is running with has access to that
# directory.
{% set configSharedFolderName = '<MODIFY>' %}
{% set downloadsSharedFolderName = '<MODIFY>' %}
{% set incompleteDownloadsSharedFolderName = '<MODIFY>' %}
# !!! Only modify the following manifest if you need to make custom changes. !!!
---
apiVersion: v1
kind: Namespace
metadata:
  name: sabnzbd-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: sabnzbd
    app.kubernetes.io/name: sabnzbd
  name: sabnzbd
  namespace: sabnzbd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: sabnzbd
      app.kubernetes.io/name: sabnzbd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: sabnzbd
        app.kubernetes.io/name: sabnzbd
    spec:
      containers:
        - name: sabnzbd
          image: linuxserver/sabnzbd:latest
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            # Specifies the UID for the process running in the container.
            runAsUser: {{ uid(runAsUser) }}
            # Specifies the GID for the process running in the container.
            runAsGroup: {{ gid(runAsGroup) }}
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
             - name: config
               mountPath: /config
             - name: downloads
               mountPath: /downloads
             - name: incomplete-downloads
               mountPath: /incomplete-downloads
      restartPolicy: Always
      volumes:
        - name: config
          hostPath:
            type: Directory
            path: {{ sharedfolder_path(configSharedFolderName) }}
        - name: downloads
          hostPath:
            type: Directory
            path: {{ sharedfolder_path(downloadsSharedFolderName) }}
        - name: incomplete-downloads
          hostPath:
            type: Directory
            path: {{ sharedfolder_path(incompleteDownloadsSharedFolderName) }}
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: sabnzbd-app
  labels:
    app.kubernetes.io/instance: sabnzbd
    app.kubernetes.io/name: sabnzbd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: sabnzbd
    app.kubernetes.io/name: sabnzbd
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sabnzbd-websecure
  namespace: sabnzbd-app
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`sabnzbd.{{ fqdn() }}`)
      kind: Rule
      services:
        - name: sabnzbd
          port: 8080
  tls: {}
