# The server can be used by configuring your MPD client to use the server at
# <FQDN> and port 6600.
# Change the following variables to adapt the recipe to your needs.
{% set runAsUser = 'nobody' %}
{% set runAsGroup = 'audio' %}
# Insert the name of the shared folder you want to use. Make sure the
# configured UID/GID the container is running with has access to that
# directory.
{% set configSharedFolderName = '<MODIFY>' %}
{% set musicSharedFolderName = '<MODIFY>' %}
# !!! Only modify the following manifest if you need to make custom changes. !!!
---
apiVersion: v1
kind: Namespace
metadata:
  name: mpd-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mpd-configmap
  namespace: mpd-app
data:
  mpd.conf.default: |
    # For more configuration options, refer to:
    #
    # - https://github.com/MusicPlayerDaemon/MPD/blob/master/doc/mpdconf.example
    # - https://mpd.readthedocs.io/en/stable/mpd.conf.5.html

    music_directory "/music"
    playlist_directory "/music"
    db_file "~/database"
    state_file "~/state"
    sticker_file "~/sticker.sql"

    audio_output {
        type            "alsa"
        name            "ALSA"
        # device          "hw:0,0"   # optional
        # mixer_type      "hardware" # optional
        # mixer_device    "default"  # optional
        # mixer_control   "PCM"      # optional
        # mixer_index     "0"        # optional
    }

    audio_output {
        type            "httpd"
        name            "MP3 Stream"
        port            "8081"
        tags            "yes"
        always_on       "no"
        encoder         "lame"
        bitrate         "320"
        # max_clients     "10"       # optional 0=no limit
    }

    audio_output {
        type            "httpd"
        name            "FLAC Stream"
        port            "8082"
        tags            "yes"
        always_on       "no"
        encoder         "flac"
        # max_clients     "10"       # optional 0=no limit
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: mpd
    app.kubernetes.io/name: mpd
  name: mpd
  namespace: mpd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mpd
      app.kubernetes.io/name: mpd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mpd
        app.kubernetes.io/name: mpd
    spec:
      containers:
        - name: mpd
          command:
            - "/bin/sh"
            - "-c"
            - '[ ! -e "$HOME/mpd.conf" ] && cp "/etc/mpd.conf.default" "$HOME/mpd.conf" ; /usr/bin/mpd --stdout --no-daemon "$HOME/mpd.conf"'
          image: gists/mpd:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            # Specifies the UID for the process running in the container.
            runAsUser: {{ uid(runAsUser) }}
            # Specifies the GID for the process running in the container.
            runAsGroup: {{ gid(runAsGroup) }}
          env:
            - name: HOME
              value: /var/lib/mpd
          volumeMounts:
            - name: home
              mountPath: /var/lib/mpd
            - name: music
              mountPath: /music
            - name: sound-devices
              mountPath: /dev/snd
            - name: config
              mountPath: /etc/mpd.conf.default
              subPath: mpd.conf.default
      hostNetwork: true
      restartPolicy: Always
      volumes:
        - name: home
          hostPath:
            type: Directory
            path: {{ sharedfolder_path(configSharedFolderName) }}
        - name: music
          hostPath:
            type: Directory
            path: {{ sharedfolder_path(musicSharedFolderName) }}
        - name: sound-devices
          hostPath:
            type: Directory
            path: /dev/snd
        - name: config
          configMap:
            name: mpd-configmap
