# The server can be used by configuring your MPD client to use the server at
# <FQDN> and port 6600.
# Change the following variables to adapt the recipe to your needs.
{% set runAsUser = 'nobody' %}
{% set runAsGroup = 'audio' %}
# Insert the name of the shared folder you want to use. Make sure the
# configured UID/GID the container is running with has access to that
# directory.
{% set configSharedFolderName = '<MODIFY>' %}
{% set musicSharedFolderName = '<MODIFY>' %}
# The following settings can be used to configure the Icecast server. You shout
# at least set custom passwords.
{% set icecastSourcePassword = 'changeme' %}
{% set icecastRelayPassword = 'changeme' %}
{% set icecastAdminPassword = 'changeme' %}
{% set icecastAdminUsername = 'admin' %}
{% set icecastAdminEmail = 'noreply@example.com' %}
{% set icecastLocation = 'MPD server' %}
{% set icecastMaxClients = '10' %}
{% set icecastMaxSources = '1' %}
# !!! Only modify the following manifest if you need to make custom changes. !!!
---
apiVersion: v1
kind: Namespace
metadata:
  name: mpd-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mpd-configmap
  namespace: mpd-app
data:
  mpd.conf.default: |
    # For more configuration options, refer to:
    #
    # - https://github.com/MusicPlayerDaemon/MPD/blob/master/doc/mpdconf.example
    # - https://mpd.readthedocs.io/en/stable/mpd.conf.5.html

    music_directory "/music"
    playlist_directory "/music"
    db_file "~/database"
    state_file "~/state"
    sticker_file "~/sticker.sql"

    audio_output {
        type            "alsa"
        name            "ALSA"
        # device          "hw:0,0"   # optional
        # mixer_type      "hardware" # optional
        # mixer_device    "default"  # optional
        # mixer_control   "PCM"      # optional
        # mixer_index     "0"        # optional
    }

    audio_output {
      type              "shout"
      encoder           "lame"   # optional
      name              "Icecast"
      host              "localhost"
      port              "8000"
      mount             "/listen.mp3"
      bitrate           "320"
      format            "44100:16:1"
      protocol          "icecast2" # optional
      password          "{{ icecastSourcePassword }}"
      # description       "My Stream Description" # optional
      # url               "http://example.com" # optional
      # genre             "jazz"   # optional
      # public            "no"     # optional
      # timeout           "2"      # optional
      # mixer_type        "software" # optional
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: mpd
    app.kubernetes.io/name: mpd
  name: mpd
  namespace: mpd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mpd
      app.kubernetes.io/name: mpd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mpd
        app.kubernetes.io/name: mpd
    spec:
      securityContext:
        fsGroup: {{ gid(runAsGroup) }}
      containers:
        - name: mpd
          command:
            - "/bin/sh"
            - "-c"
            - '[ ! -e "$HOME/mpd.conf" ] && cp "/etc/mpd.conf.default" "$HOME/mpd.conf" ; /usr/bin/mpd --stdout --no-daemon "$HOME/mpd.conf"'
          image: gists/mpd:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            # Specifies the UID for the process running in the container.
            runAsUser: {{ uid(runAsUser) }}
            # Specifies the GID for the process running in the container.
            runAsGroup: {{ gid(runAsGroup) }}
          env:
            - name: HOME
              value: /var/lib/mpd
          ports:
            - name: mpd-tcp
              protocol: TCP
              containerPort: 6600
          volumeMounts:
            - name: home
              mountPath: /var/lib/mpd
            - name: music
              mountPath: /music
            - name: sound-devices
              mountPath: /dev/snd
            - name: mpd-config
              mountPath: /etc/mpd.conf.default
              subPath: mpd.conf.default
        - name: icecast2
          image: libretime/icecast:2.4.4-alpine
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            # Specifies the UID for the process running in the container.
            runAsUser: 1000  # Needs to be the "icecast" user
            # Specifies the GID for the process running in the container.
            runAsGroup: {{ gid(runAsGroup) }}
          env:
            - name: ICECAST_SOURCE_PASSWORD
              value: "{{ icecastSourcePassword }}"
            - name: ICECAST_RELAY_PASSWORD
              value: "{{ icecastRelayPassword }}"
            - name: ICECAST_ADMIN_PASSWORD
              value: "{{ icecastAdminPassword }}"
            - name: ICECAST_ADMIN_USERNAME
              value: "{{ icecastAdminUsername }}"
            - name: ICECAST_ADMIN_EMAIL
              value: "{{ icecastAdminEmail }}"
            - name: ICECAST_LOCATION
              value: "{{ icecastLocation }}"
            - name: ICECAST_HOSTNAME
              value: "icecast.mpd.{{ fqdn() }}"
            - name: ICECAST_MAX_CLIENTS
              value: "{{ icecastMaxClients }}"
            - name: ICECAST_MAX_SOURCES
              value: "{{ icecastMaxSources }}"
          ports:
            - name: stream
              protocol: TCP
              containerPort: 8000
        - name: mympd
          image: ghcr.io/jcorporation/mympd/mympd:latest
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            # Specifies the UID for the process running in the container.
            runAsUser: {{ uid(runAsUser) }}
            # Specifies the GID for the process running in the container.
            runAsGroup: {{ gid(runAsGroup) }}
          env:
            - name: MPD_HOST
              value: localhost
            - name: UMASK_SET
              value: "022"
            - name: MYMPD_SSL
              value: "false"
            - name: MYMPD_HTTP_PORT
              value: "8080"
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
             - name: mympd-workdir
               mountPath: /var/lib/mympd
             - name: mympd-cachedir
               mountPath: /var/cache/mympd
      restartPolicy: Always
      volumes:
        - name: home
          hostPath:
            type: Directory
            path: {{ sharedfolder_path(configSharedFolderName) }}
        - name: music
          hostPath:
            type: Directory
            path: {{ sharedfolder_path(musicSharedFolderName) }}
        - name: sound-devices
          hostPath:
            type: Directory
            path: /dev/snd
        - name: mpd-config
          configMap:
            name: mpd-configmap
        - name: mympd-workdir
          hostPath:
            type: DirectoryOrCreate
            path: "{{ sharedfolder_path(configSharedFolderName) }}/mympd"
        - name: mympd-cachedir
          emptyDir:
            sizeLimit: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mpd
  namespace: mpd-app
  labels:
    app.kubernetes.io/instance: mpd
    app.kubernetes.io/name: mpd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: mpd
    app.kubernetes.io/name: mpd
  ports:
    - name: mpd-tcp
      protocol: TCP
      port: 6600
      targetPort: 6600
    - name: icecast
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: mympd
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: icecast
  namespace: mpd-app
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`icecast.mpd.{{ fqdn() }}`)
      kind: Rule
      services:
        - name: mpd
          port: 8000
    - match: Host(`mpd.{{ fqdn() }}`)
      kind: Rule
      services:
        - name: mpd
          port: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mpd-tcp
  namespace: mpd-app
spec:
  entryPoints:
    - mpd
  routes:
  - match: HostSNI(`*`)
    priority: 10
    services:
    - name: mpd
      port: 6600
      weight: 10
