# The app can be reached at https://headlamp.<FQDN>:8443
{% set hostname = 'headlamp.' ~ fqdn() %}
# Alternatively, use sslip.io if you don't have a local DNS server.
# The app can then be reached at: https://headlamp.<IP>.sslip.io:8443
# {% set hostname = 'headlamp.' ~ ipaddr() ~ '.sslip.io' %}
# !!! Only modify the following manifest if you need to make custom changes. !!!
---
apiVersion: v1
kind: Namespace
metadata:
  name: headlamp-app
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: headlamp
  namespace: kube-system
  labels:
    app.kubernetes.io/name: headlamp
spec:
  repo: https://kubernetes-sigs.github.io/headlamp/
  chart: headlamp
  targetNamespace: headlamp-app
  valuesContent: |-
    image:
      tag: latest
    serviceAccount:
      name: headlamp-admin
    service:
      port: 4466
---
apiVersion: v1
kind: Secret
metadata:
  name: headlamp-admin
  namespace: headlamp-app
  labels:
    app.kubernetes.io/name: headlamp
  annotations:
    kubernetes.io/service-account.name: "headlamp-admin"
type: kubernetes.io/service-account-token
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp-websecure
  namespace: headlamp-app
  labels:
    app.kubernetes.io/name: headlamp
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ hostname }}`)
      kind: Rule
      services:
        - name: headlamp
          port: 4466
  tls: {}
