# The app can be reached at https://ollama.<FQDN>:8443
# Change the following variables to adapt the recipe to your needs.
# Insert the name of the shared folder you want to use. Make sure the
# configured UID/GID the container is running with has access to that
# directory.
{% set dataSharedFolderName = '<MODIFY>' %}
# !!! Only modify the following manifest if you need to make custom changes. !!!
---
apiVersion: v1
kind: Namespace
metadata:
  name: ollama-app
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ollama
  namespace: ollama-app
  labels:
    app.kubernetes.io/instance: ollama
    app.kubernetes.io/name: ollama
spec:
  repo: https://otwld.github.io/ollama-helm/
  chart: ollama
  targetNamespace: ollama-app
  valuesContent: |-
    image:
      tag: latest
    deployment:
      labels:
        app.kubernetes.io/instance: ollama
        app.kubernetes.io/name: ollama
    podLabels:
      app.kubernetes.io/instance: ollama
      app.kubernetes.io/name: ollama
    persistentVolume:
      enabled: true
      storageClass: shared-folder
      volumeName: data-dir
    ollama:
      selectorLabels:
        app.kubernetes.io/instance: ollama
        app.kubernetes.io/name: ollama
      # The available model names can be found at https://ollama.com/library.
      # Keep in mind that the models require a lot of disk storage and RAM.
      models:
        pull:
          - gemma3:1b
        run:
          - gemma3:1b
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-dir
  labels:
    app.kubernetes.io/instance: ollama
    app.kubernetes.io/name: ollama
spec:
  storageClassName: shared-folder
  capacity:
    storage: 30Gi
  hostPath:
    # Insert the name of the shared folder you want to use.
    # Make sure the configured UID/GID the container is running
    # with has access to that directory.
    path: {{ sharedfolder_path(dataSharedFolderName) }}
    type: Directory
  accessModes:
    - ReadWriteOnce
---
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: ollama-websecure
#   namespace: ollama-app
#   labels:
#     app.kubernetes.io/instance: ollama
#     app.kubernetes.io/name: ollama
# spec:
#   entryPoints:
#     - websecure
#   routes:
#     - match: Host(`ollama.{{ fqdn() }}`)
#       kind: Rule
#       services:
#         - name: ollama
#           port: 11434
#   tls: {}
