# The app can be reached at https://piwigo.<FQDN>:8443
# Use `mariadb` in the `MySQL-Host` form field.
# Change the following variables to adapt the recipe to your needs.
{% set dbName = 'piwigo' %}
{% set dbUser = 'piwigo' %}
{% set dbPassword = 'piwigo' %}
{% set dbRootPassword = 'piwigo' %}
{% set runAsUser = 'nobody' %}
{% set runAsGroup = 'users' %}
# Insert the name of the shared folder you want to use. Make sure the
# configured UID/GID the container is running with has access to that
# directory.
{% set configSharedFolderName = '<MODIFY>' %}
{% set gallerySharedFolderName = '<MODIFY>' %}
{% set dbSharedFolderName = '<MODIFY>' %}
# !!! Only modify the following manifest if you need to make custom changes. !!!
---
apiVersion: v1
kind: Namespace
metadata:
  name: piwigo-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: piwigo-env
  namespace: piwigo-app
data:
  PUID: "{{ uid(runAsUser) }}"
  PGID: "{{ gid(runAsGroup) }}"
  TZ: "{{ tz() }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-env
  namespace: piwigo-app
  labels:
    app.kubernetes.io/instance: piwigo
    app.kubernetes.io/name: piwigo
data:
  MARIADB_DATABASE: "{{ dbName }}"
  MARIADB_USER: "{{ dbUser }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  namespace: piwigo-app
  labels:
    app.kubernetes.io/instance: piwigo
    app.kubernetes.io/name: piwigo
stringData:
  MARIADB_PASSWORD: "{{ dbPassword }}"
  MARIADB_ROOT_PASSWORD: "{{ dbRootPassword }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: piwigo
    app.kubernetes.io/name: piwigo
  name: piwigo
  namespace: piwigo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: piwigo
      app.kubernetes.io/name: piwigo
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: piwigo
        app.kubernetes.io/name: piwigo
    spec:
      containers:
        - name: piwigo
          image: lscr.io/linuxserver/piwigo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: piwigo-env
          volumeMounts:
            - name: "config"
              mountPath: "/config"
            - name: "gallery"
              mountPath: "/gallery"
        - name: mariadb
          image: docker.io/mariadb:11
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          securityContext:
            runAsNonRoot: true
            # Specifies the UID for the process running in the container.
            runAsUser: {{ uid(runAsUser) }}
            # Specifies the GID for the process running in the container.
            # Defaults to `users`.
            runAsGroup: {{ gid(runAsGroup) }}
          envFrom:
            - secretRef:
                name: mariadb
            - configMapRef:
                name: mariadb-env
          volumeMounts:
            - name: "db"
              mountPath: /var/lib/mysql
      restartPolicy: Always
      volumes:
        - name: "config"
          hostPath:
            type: "Directory"
            # Insert the name of the shared folder you want to use.
            # Make sure the configured UID/GID the container is running
            # with has access to that directory.
            path: "{{ sharedfolder_path(configSharedFolderName) }}"
        - name: "gallery"
          hostPath:
            type: "Directory"
            # Insert the name of the shared folder you want to use.
            # Make sure the configured UID/GID the container is running
            # with has access to that directory.
            path: "{{ sharedfolder_path(gallerySharedFolderName) }}"
        - name: "db"
          hostPath:
            type: Directory
            # Insert the name of the shared folder you want to use.
            # Make sure the configured UID/GID the container is running
            # with has access to that directory.
            path: {{ sharedfolder_path(dbSharedFolderName) }}
---
apiVersion: v1
kind: Service
metadata:
  name: piwigo
  namespace: piwigo-app
  labels:
    app.kubernetes.io/instance: piwigo
    app.kubernetes.io/name: piwigo
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/instance: piwigo
    app.kubernetes.io/name: piwigo
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: piwigo-app
  labels:
    app.kubernetes.io/instance: piwigo
    app.kubernetes.io/name: piwigo
spec:
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app.kubernetes.io/instance: piwigo
    app.kubernetes.io/name: piwigo
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: piwigo-websecure
  namespace: piwigo-app
  labels:
    app.kubernetes.io/instance: piwigo
    app.kubernetes.io/name: piwigo
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`piwigo.{{ fqdn() }}`)
      kind: Rule
      services:
        - name: piwigo
          port: 80
  tls: {}
