# The app can be reached at https://firefox.<FQDN>:8443
# Change the following variables to adapt the recipe to your needs.
{% set user = 'admin' %}
{% set password = 'firefox' %}
{% set runAsUser = 'nobody' %}
{% set runAsGroup = 'users' %}
# Insert the name of the shared folder you want to use. Make sure the
# configured UID/GID the container is running with has access to that
# directory.
{% set configSharedFolderName = '<MODIFY>' %}
# !!! Only modify the following manifest if you need to make custom changes. !!!
---
apiVersion: v1
kind: Namespace
metadata:
  name: firefox-app
---
apiVersion: v1
kind: Secret
metadata:
  name: firefox
  namespace: firefox-app
  labels:
    app.kubernetes.io/instance: firefox
    app.kubernetes.io/name: firefox
stringData:
  PASSWORD: "{{ password }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: firefox-env
  namespace: firefox-app
data:
  CUSTOM_USER: "{{ user }}"
  PUID: "{{ uid(runAsUser) }}"
  PGID: "{{ gid(runAsGroup) }}"
  TZ: "{{ tz() }}"
  FIREFOX_CLI: "https://www.openmediavault.org"
  LC_ALL: "en_US.UTF-8"
  NO_DECOR: "1"
  DOCKER_MODS: "linuxserver/mods:universal-package-install"
  INSTALL_PACKAGES: "fonts-noto-cjk"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: firefox
    app.kubernetes.io/name: firefox
  name: firefox
  namespace: firefox-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: firefox
      app.kubernetes.io/name: firefox
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: firefox
        app.kubernetes.io/name: firefox
    spec:
      containers:
        - name: firefox
          image: lscr.io/linuxserver/firefox:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - secretRef:
                name: firefox
                optional: false
            - configMapRef:
                name: firefox-env
          volumeMounts:
            - name: "config"
              mountPath: "/config"
      restartPolicy: Always
      volumes:
        - name: "config"
          hostPath:
            type: "Directory"
            # Insert the name of the shared folder you want to use.
            # Make sure the configured UID/GID the container is running
            # with has access to that directory.
            path: "{{ sharedfolder_path(configSharedFolderName) }}"
---
apiVersion: v1
kind: Service
metadata:
  name: firefox
  namespace: firefox-app
  labels:
    app.kubernetes.io/instance: firefox
    app.kubernetes.io/name: firefox
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/instance: firefox
    app.kubernetes.io/name: firefox
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: firefox-websecure
  namespace: firefox-app
  labels:
    app.kubernetes.io/instance: firefox
    app.kubernetes.io/name: firefox
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`firefox.{{ fqdn() }}`)
      kind: Rule
      services:
        - name: firefox
          port: 3000
  tls: {}
