# The app can be reached at https://minio-console.<FQDN>:8443
# Change the following variables to adapt the recipe to your needs.
{% set runAsUser = 'nobody' %}
{% set runAsGroup = 'users' %}
# Insert the name of the shared folder you want to use. Make sure the
# configured UID/GID the container is running with has access to that
# directory.
{% set dataSharedFolderName = '<MODIFY>' %}
# !!! Only modify the following manifest if you need to make custom changes. !!!
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: minio
    app.kubernetes.io/name: minio
  name: minio
  namespace: minio-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: minio
      app.kubernetes.io/name: minio
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: minio
        app.kubernetes.io/name: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: true
          # Specifies the UID for the process running in the container.
          runAsUser: {{ uid(runAsUser) }}
          # Specifies the GID for the process running in the container.
          runAsGroup: {{ gid(runAsGroup) }}
        args:
        - "server"
        - "/data/"
        env:
        - name: "MINIO_ADDRESS"
          value: ":9000"
        - name: "MINIO_CONSOLE_ADDRESS"
          value: ":9001"
        - name: "MINIO_ROOT_USER"
          value: "admin"
        - name: "MINIO_ROOT_PASSWORD"
          value: "openmediavault"
        ports:
        - containerPort: 9000
          name: api
          protocol: TCP
        - containerPort: 9001
          name: console
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: "/data/"
      restartPolicy: Always
      volumes:
      - name: data
        hostPath:
          type: Directory
          # Insert the name of the shared folder you want to use.
          # Make sure the configured UID/GID the container is running
          # with has access to that directory.
          path: {{ sharedfolder_path(dataSharedFolderName) }}
---
apiVersion: v1
kind: Service
metadata:
  name: minio-api
  namespace: minio-app
spec:
  selector:
    app.kubernetes.io/instance: minio
    app.kubernetes.io/name: minio
  type: ClusterIP
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: minio-app
  labels:
    app.kubernetes.io/instance: minio
    app.kubernetes.io/name: minio
spec:
  selector:
    app.kubernetes.io/instance: minio
    app.kubernetes.io/name: minio
  type: ClusterIP
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-console-websecure
  namespace: minio-app
  labels:
    app.kubernetes.io/instance: minio
    app.kubernetes.io/name: minio
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`minio-console.{{ fqdn() }}`)
    kind: Rule
    services:
    - name: minio-console
      port: 9001
  tls: {}
