# The app can be reached at http://forgejo.<FQDN>:8080
# Change the following variables to adapt the recipe to your needs.
{% set runAsUser = 'nobody' %}
{% set runAsGroup = 'users' %}
# Insert the name of the shared folder you want to use. Make sure the
# configured UID/GID the container is running with has access to that
# directory.
{% set homeSharedFolderName = '<MODIFY>' %}
{% set configSharedFolderName = '<MODIFY>' %}
# !!! Only modify the following manifest if you need to make custom changes. !!!
---
apiVersion: v1
kind: Namespace
metadata:
  name: forgejo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: forgejo
    app.kubernetes.io/name: forgejo
  name: forgejo
  namespace: forgejo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: forgejo
      app.kubernetes.io/name: forgejo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: forgejo
        app.kubernetes.io/name: forgejo
    spec:
      containers:
        - name: forgejo
          image: codeberg.org/forgejo/forgejo:12-rootless
          imagePullPolicy: Always
          env:
            - name: USER_UID
              value: "{{ uid(runAsUser) }}"
            - name: USER_GID
              value: "{{ gid(runAsGroup) }}"
            - name: FORGEJO__server__DOMAIN
              value: "forgejo.{{ fqdn() }}"
            - name: FORGEJO__server__ROOT_URL
              value: "https://forgejo.{{ fqdn() }}:{{ conf_get('conf.service.k8s'") | get('websecureport') }}/"
            - name: FORGEJO__server__SSH_DOMAIN
              value: "{{ fqdn() }}"
            - name: FORGEJO__server__SSH_PORT
              value: "2222"
            - name: FORGEJO__server__SSH_LISTEN_PORT
              value: "2222"
          securityContext:
            runAsNonRoot: true
            # Specifies the UID for the process running in the container.
            runAsUser: {{ uid(runAsUser) }}
            # Specifies the GID for the process running in the container.
            runAsGroup: {{ gid(runAsGroup) }}
          ports:
            - name: http
              protocol: TCP
              containerPort: 3000
            - name:
              protocol: TCP
              containerPort: 2222
              hostPort: 2222
          volumeMounts:
             - name: home
               mountPath: /var/lib/gitea
             - name: config
               mountPath: /etc/gitea
             - name: timezone
               mountPath: /timezone
               readOnly: true
             - name: localtime
               mountPath: /etc/localtime
               readOnly: true
      restartPolicy: Always
      volumes:
        - name: home
          hostPath:
            type: Directory
            path: {{ sharedfolder_path(homeSharedFolderName) }}
        - name: config
          hostPath:
            type: Directory
            path: {{ sharedfolder_path(configSharedFolderName) }}
        - name: timezone
          hostPath:
            type: File
            path: /etc/timezone
        - name: localtime
          hostPath:
            type: File
            path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: forgejo
  namespace: forgejo-app
  labels:
    app.kubernetes.io/instance: forgejo
    app.kubernetes.io/name: forgejo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: forgejo
    app.kubernetes.io/name: forgejo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: forgejo-websecure
  namespace: forgejo-app
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`forgejo.{{ fqdn() }}`)
      kind: Rule
      services:
        - name: forgejo
          port: 3000
  tls: {}
