# The app can be reached at https://filebrowser.<FQDN>:8443
# Change the following variables to adapt the recipe to your needs.
{% set runAsUser = 'nobody' %}
{% set runAsGroup = 'users' %}
# Insert the name of the shared folder you want to use. Make sure the
# configured UID/GID the container is running with has access to that
# directory.
{% set rootSharedFolderName = '<MODIFY>' %}
# !!! Only modify the following manifest if you need to make custom changes. !!!
---
apiVersion: v1
kind: Namespace
metadata:
  name: filebrowser-app
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: filebrowser
  namespace: filebrowser-app
  labels:
    app.kubernetes.io/instance: filebrowser
    app.kubernetes.io/name: filebrowser
spec:
  repo: https://utkuozdemir.org/helm-charts
  chart: filebrowser
  version: "1.0.0"
  targetNamespace: filebrowser-app
  valuesContent: |-
    image:
      tag: "v2.32.3"
    securityContext:
      runAsNonRoot: true
      # Specifies the UID for the process running in the container.
      runAsUser: {{ uid(runAsUser) }}
      # Specifies the GID for the process running in the container.
      runAsGroup: {{ gid(runAsGroup) }}
    rootDir:
      type: hostPath
      hostPath:
        # Insert the name of the shared folder you want to use.
        # Make sure the configured UID/GID the container is running
        # with has access to that directory.
        path: {{ sharedfolder_path(rootSharedFolderName) }}
    config:
      baseURL: /
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: filebrowser-websecure
  namespace: filebrowser-app
  labels:
    app.kubernetes.io/instance: filebrowser
    app.kubernetes.io/name: filebrowser
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`filebrowser.{{ fqdn() }}`)
      kind: Rule
      services:
        - name: filebrowser
          port: 80
  tls: {}
