# The app can be reached at https://jellyfin.<FQDN>:8443
# Change the following variables to adapt the recipe to your needs.
{% set runAsUser = 'nobody' %}
{% set runAsGroup = 'users' %}
# Insert the name of the shared folder you want to use. Make sure the
# configured UID/GID the container is running with has access to that
# directory.
{% set cacheSharedFolderName = '<MODIFY>' %}
{% set configSharedFolderName = '<MODIFY>' %}
{% set mediaSharedFolderName = '<MODIFY>' %}
# !!! Only modify the following manifest if you need to make custom changes. !!!
---
apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/name: jellyfin
  name: jellyfin
  namespace: jellyfin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: jellyfin
      app.kubernetes.io/name: jellyfin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: jellyfin
        app.kubernetes.io/name: jellyfin
    spec:
      containers:
        - image: docker.io/jellyfin/jellyfin:latest
          imagePullPolicy: IfNotPresent
          name: jellyfin
          ports:
            - containerPort: 8096
              name: http
              protocol: TCP
          securityContext:
            runAsNonRoot: true
            # Specifies the UID for the process running in the container.
            runAsUser: {{ uid(runAsUser) }}
            # Specifies the GID for the process running in the container.
            runAsGroup: {{ gid(runAsGroup) }}
          volumeMounts:
            - name: cache
              mountPath: /cache
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
      restartPolicy: Always
      volumes:
        - name: cache
          hostPath:
            type: Directory
            # Insert the name of the shared folder you want to use.
            # Make sure the configured UID/GID the container is running
            # with has access to that directory.
            path: {{ sharedfolder_path(cacheSharedFolderName) }}
        - name: config
          hostPath:
            type: Directory
            # Insert the name of the shared folder you want to use.
            # Make sure the configured UID/GID the container is running
            # with has access to that directory.
            path: {{ sharedfolder_path(configSharedFolderName) }}
        - name: media
          hostPath:
            type: Directory
            # Insert the name of the shared folder you want to use.
            # Make sure the configured UID/GID the container is running
            # with has access to that directory.
            path: {{ sharedfolder_path(mediaSharedFolderName) }}
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin-app
  labels:
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/name: jellyfin
spec:
  type: ClusterIP
  ports:
    - port: 8096
      protocol: TCP
      targetPort: 8096
  selector:
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/name: jellyfin
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin-websecure
  namespace: jellyfin-app
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellyfin.{{ fqdn() }}`)
      kind: Rule
      services:
        - name: jellyfin
          port: 8096
  tls: {}
