# The app can be reached at https://wetty.<FQDN>:8443
# Change the following variables to adapt the recipe to your needs.
{% set runAsUser = 'nobody' %}
{% set runAsGroup = 'nogroup' %}
# !!! Only modify the following manifest if you need to make custom changes. !!!
---
apiVersion: v1
kind: Namespace
metadata:
  name: wetty-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: wetty
    app.kubernetes.io/name: wetty
  name: wetty
  namespace: wetty-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: wetty
      app.kubernetes.io/name: wetty
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: wetty
        app.kubernetes.io/name: wetty
    spec:
      containers:
        - image: docker.io/wettyoss/wetty:latest
          imagePullPolicy: IfNotPresent
          name: wetty
          ports:
            - containerPort: 3000
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ uid(runAsUser) }}
            runAsGroup: {{ gid(runAsGroup) }}
          args:
            - "--port=3000"
            - "--base=/"
            - "--force-ssh"
            - "--ssh-port={{ conf_get('conf.service.ssh') | get('port') }}"
            - "--ssh-host={{ hostname() }}"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: wetty
  namespace: wetty-app
  labels:
    app.kubernetes.io/instance: wetty
    app.kubernetes.io/name: wetty
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/instance: wetty
    app.kubernetes.io/name: wetty
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wetty-websecure
  namespace: wetty-app
  labels:
    app.kubernetes.io/instance: wetty
    app.kubernetes.io/name: wetty
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`wetty.{{ fqdn() }}`)
      kind: Rule
      services:
        - name: wetty
          port: 3000
  tls: {}
